version: '3'

services:

  lims_db:
    image: mongo:5.0.9
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - mongodb-data:${MONGODB_DATA_DIR}

    ports:
      - "27013:${DB_PORT}"
    networks:
      - monstre

  lims_server:
    build: ./server
    container_name: "${API_HOST}"
    volumes:
      - ./projects:/server/projects
    restart: always
    env_file:
      - .env
    networks:
      - monstre

  lims_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "lims-client"
    restart: always
    volumes:
      - node_modules:/client/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lims_client.rule=Host(`genome.crg.es`) && Path(`/lims`)"
      - "traefik.http.routers.lims_client.tls=true"
      - "traefik.http.routers.lims_client.entrypoints=web_https"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/lims"

    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}

    networks:
      - monstre

volumes:
  mongodb-data:
  node_modules:


networks:
  monstre:
    external:
      name: monstre
