version: '3'

services:

  lims_db:
    image: mongo
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - mongodb-data:${MONGODB_DATA_DIR}

    ports:
      - "27013:${DB_PORT}"

  lims_server:
    build: ./server
    container_name: "${API_HOST}"
    restart: always
    ports:
     - 5010:5000
    volumes:
      - ./server:/server
      - ./project-spec.json:/server/project-spec.json
      - ./project-spec-v2.json:/server/project-spec-v2.json
      - ./protocols:/server/protocols # store protocols here (pdf, txt, doc)
      - ./images:/server/images # store pictures here (jpeg, png)
    env_file:
      - .env

  lims_client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - BASE_PATH=$BASE_PATH
    container_name: "lims_client"
    restart: always
    volumes:
      - node_modules:/client/node_modules

    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - BASE_PATH=${BASE_PATH}
    ports:
        - "93:${API_PORT}"

volumes:
  mongodb-data:
  node_modules:
