version: '3'

services:

  DB_LIMS:
    image: mongo:5.0.9
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "27013:${DB_PORT}"

  lims_server:
    image: gitlab.linux.crg.es:5005/monstre/lims/lims_server
    restart: always
    env_file:
      - .env

  lims_client:
    image: gitlab.linux.crg.es:5005/monstre/lims/lims_client
    restart: always
    volumes:
      - node_modules:/client/node_modules

    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    ports:
        - "93:${API_PORT}"

volumes:
  mongodb-data:
  node_modules:
