version: '3'

services:

  DB_LIMS:
    image: mongo
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - mongodb-data:${MONGODB_DATA_DIR}

    ports:
      - "27013:${DB_PORT}"

  lims_server:
    build: ./server
    container_name: "${API_HOST}"
    restart: always
    env_file:
      - .env

  lims_client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - BASE_PATH=$BASE_PATH
    container_name: "lims_client"
    restart: always
    volumes:
      - node_modules:/client/node_modules

    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - BASE_PATH=${BASE_PATH}
    ports:
        - "93:${API_PORT}"

volumes:
  mongodb-data:
  node_modules:
